name: "CI build"
on:
  push:
    branches:
      - main
jobs:
  build-application-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get result
        run: env   
      - name: FreezeCheck
        uses: amar-khan/check-prod-freeze@main
        with:
          env: 'prod'
          force_deploy: false
          freezeStart: "16:00"
          freezeEnd: "17:30"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
